import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import fs from 'fs';
import path from 'path';

const MUSIC_DIR   = 'public/music';
const TRACKS_FILE = 'src/data/tracks.js';
const AUDIO_EXTS  = new Set(['.mp3', '.wav', '.ogg', '.flac', '.m4a', '.aac']);

function toTitle(filename) {
  return filename
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

function scanAndWrite(root) {
  const musicDir = path.join(root, MUSIC_DIR);
  const dest     = path.join(root, TRACKS_FILE);

  let files = [];
  try {
    files = fs.readdirSync(musicDir).filter(f => AUDIO_EXTS.has(path.extname(f).toLowerCase()));
  } catch {
    // folder doesn't exist yet — write an empty list
  }

  files.sort();

  const entries = files.map((f, i) => {
    const name = path.basename(f, path.extname(f));
    const title = toTitle(name);
    return `  { id: ${i + 1}, title: '${title}', artist: 'Unknown', file: '${f}' }`;
  });

  const content =
    `// AUTO-GENERATED by Vite plugin — do not edit by hand.\n` +
    `// Drop audio files into public/music/ and this file updates automatically.\n` +
    `// To customise a title or artist, rename the file (hyphens/underscores become spaces).\n\n` +
    `export const TRACKS = [\n${entries.join(',\n')}\n];\n`;

  const existing = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : '';
  if (existing !== content) {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content, 'utf8');
    console.log(`[music-scanner] tracks.js updated — ${files.length} track(s)`);
  }
}

function musicScannerPlugin() {
  let root;
  let watcher;

  return {
    name: 'music-scanner',
    configResolved(config) {
      root = config.root;
    },
    buildStart() {
      scanAndWrite(root);

      // Watch only during dev (watcher is undefined during build)
      if (this.meta.watchMode) {
        const musicDir = path.join(root, MUSIC_DIR);
        fs.mkdirSync(musicDir, { recursive: true });

        watcher = fs.watch(musicDir, () => scanAndWrite(root));
        watcher.on('error', () => {});
      }
    },
    closeBundle() {
      watcher?.close();
    },
  };
}

export default defineConfig({
  plugins: [musicScannerPlugin(), react()],
});
